{
 "title": "HTTP Request Observability",
 "tags": [
  "prometheus",
  "http",
  "latency"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Latency p95 por Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le,endpoint,method,code))",
     "legendFormat": "{{endpoint}} {{method}} p95"
    }
   ]
  },
  {
   "title": "Latency p99 por Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[5m])) by (le,endpoint,method,code))",
     "legendFormat": "{{endpoint}} {{method}} p99"
    }
   ]
  },
  {
   "title": "Throughput (Requests por segundo)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[1m])) by (endpoint,method)",
     "legendFormat": "{{endpoint}} {{method}}"
    }
   ]
  },
  {
   "title": "Taxa de Erros (>= 400)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{code!~\"2..\"}[5m])) / sum(rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "Taxa de erros"
    }
   ]
  },
  {
   "title": "Tempo médio das requisições",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[5m])) / sum(rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "Média Geral"
    }
   ]
  },
  {
   "title": "Heatmap de Latência (buckets)",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket[5m])) by (le)"
    }
   ]
  },
  {
   "title": "Resumo por Endpoint",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (endpoint,method,code) (rate(http_request_duration_seconds_count[5m]))"
    },
    {
     "expr": "sum by (endpoint,method,code) (rate(http_request_duration_seconds_sum[5m]))"
    }
   ]
  }
 ]
}