{
 "title": "salescarweb",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Application Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Duration Seconds Sum",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum",
     "legendFormat": "{{action}} - {{endpoint}}"
    }
   ]
  },
  {
   "title": "Requests Received Total",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_received_total", "legendFormat": "{{action}} - {{endpoint}}" }
   ]
  },
  {
   "title": "Requests Failed Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_hosting_failed_requests",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Num Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "process_num_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Memory Bytes Allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "dotnet_total_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "expr": "system_runtime_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  { "title": "Business Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Anúncios Exibidos",
   "type": "gauge",
   "description": "Quantidade de vezes que a tela de Anúncios foi visitada",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "AnunciosConsultados", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Anúncios Vistos",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "AnuncioConsultado", "legendFormat": "__auto" }
   ]
  }
 ]
}