version: "3.1"

services:
  # appdynamics:
  #   image: appdynamics/cluster-agent
  #   environment:
  #     - APPDYNAMICS_AGENT_APPLICATION_NAME=CManager
  #     - APPDYNAMICS_AGENT_TIER_NAME=CManager
  #     - APPDYNAMICS_AGENT_NODE_NAME=CManager
  #   ports:
  #     - "8090:8090"
  #   volumes:
  #     - shared_volume:/app/agent-files
  #   networks:
  #     - my_network

  web:
    build: .
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
      - shared_volume:/app/agent-files
    networks:
      - my_network
    # depends_on:
    #   - appdynamics

  prometheus:
    build:
      context: .
      dockerfile: dockerfile-prometheus.yml
    ports:
      - "9090:9090"
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    depends_on:
      - appdynamics

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

networks:
  my_network:
    external:
      name: my_network

# volumes:
#   shared_volume:  