version: "3.1"

services:
  web:
    build: .
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - C:/CManager/CManager/src/CManager/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - C:/CManager/CManager/src/CManager/.aspnet/https:/root/.aspnet/https/
    networks:
      - my_network

  prometheus:
    build:
      context: .
      dockerfile: dockerfile-prometheus.yml
    ports:
      - "9090:9090"
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

configs:
  prometheus_config:
    file: ./prometheus.yml

networks:
  my_network:
    external: true