version: '3.1'

services:
  web:
    build: .
    ports:
        - "8000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
        - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
        - ${HOME}/.aspnet/https:/root/.aspnet/https/
    networks:
      - my_network

  prometheus:
    build: 
      context: .
      dockerfile: dockerfile-prometheus.yml
    ports:
      - "9090:9090"
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    depends_on:
      - web
  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3001:3000"   
    depends_on:
      - prometheus

networks:
  my_network:
    external:
      name: my_network