global:
  scrape_interval: 10s
  scrape_timeout: 5s

scrape_configs:
  - job_name: "businessmotorsapi"
    honor_timestamps: true
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - salescarapi:80