{{- if .Values.adminer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  labels:
    {{- include "businessmotors.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
        {{- include "businessmotors.labels" . | nindent 8 }}
    spec:
      containers:
        - name: adminer
          image: "{{ .Values.adminer.image.repository }}:{{ .Values.adminer.image.tag }}"
          imagePullPolicy: {{ .Values.adminer.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: adminer-config
          resources:
            {{- toYaml .Values.adminer.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
{{- end }}