{{- if and .Values.mysql.enabled .Values.mysql.auth.createSecret (not .Values.mysql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    {{- include "businessmotors.labels" . | nindent 4 }}
type: Opaque
stringData:
  root-password: {{ .Values.mysql.auth.rootPassword | quote }}
  database: {{ .Values.mysql.auth.database | quote }}
  user: {{ .Values.mysql.auth.username | quote }}
  password: {{ .Values.mysql.auth.password | quote }}
  connection-string: {{ .Values.mysql.auth.connectionString | default (printf "Server=mysql.%s.svc.cluster.local;Port=3306;Database=%s;Uid=%s;Pwd=%s" .Release.Namespace .Values.mysql.auth.database .Values.mysql.auth.username .Values.mysql.auth.password) | quote }}
{{- end }}