{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    {{- include "businessmotors.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}
  {{- with .Values.mysql.persistence.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}